"""Esquema original del proyecto, congelado para migraciones reproducibles."""

from alembic import op
import sqlalchemy as sa

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categorias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_categorias_id"), "categorias", ["id"], unique=False)
    op.create_index(op.f("ix_categorias_nombre"), "categorias", ["nombre"], unique=True)
    op.create_table(
        "proveedores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("contacto", sa.String(length=100), nullable=True),
        sa.Column("condiciones_comerciales", sa.Text(), nullable=True),
        sa.Column("tiempo_entrega_promedio_dias", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "tiempo_entrega_promedio_dias >= 0", name="check_tiempo_entrega_positivo"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_proveedores_id"), "proveedores", ["id"], unique=False)
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=50), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    op.create_index(op.f("ix_roles_nombre"), "roles", ["nombre"], unique=True)
    op.create_table(
        "sucursales",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("ubicacion", sa.String(length=255), nullable=False),
        sa.Column("activa", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sucursales_id"), "sucursales", ["id"], unique=False)
    op.create_index(op.f("ix_sucursales_nombre"), "sucursales", ["nombre"], unique=True)
    op.create_table(
        "productos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sku", sa.String(length=100), nullable=False),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("categoria_id", sa.Integer(), nullable=False),
        sa.Column("unidad_medida", sa.String(length=50), nullable=False),
        sa.Column("stock_minimo_global", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "stock_minimo_global >= 0", name="check_stock_minimo_global_positivo"
        ),
        sa.ForeignKeyConstraint(
            ["categoria_id"],
            ["categorias.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_productos_id"), "productos", ["id"], unique=False)
    op.create_index(op.f("ix_productos_sku"), "productos", ["sku"], unique=True)
    op.create_table(
        "usuarios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=150), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("rol_id", sa.Integer(), nullable=False),
        sa.Column("sucursal_id", sa.Integer(), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rol_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sucursal_id"],
            ["sucursales.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usuarios_email"), "usuarios", ["email"], unique=True)
    op.create_index(op.f("ix_usuarios_id"), "usuarios", ["id"], unique=False)
    op.create_table(
        "inventario_sucursal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sucursal_id", sa.Integer(), nullable=False),
        sa.Column("producto_id", sa.Integer(), nullable=False),
        sa.Column("stock_actual", sa.Integer(), nullable=False),
        sa.Column("stock_minimo_local", sa.Integer(), nullable=False),
        sa.Column(
            "costo_promedio_ponderado",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
        ),
        sa.CheckConstraint(
            "costo_promedio_ponderado >= 0", name="check_costo_promedio_positivo"
        ),
        sa.CheckConstraint("stock_actual >= 0", name="check_stock_actual_positivo"),
        sa.CheckConstraint(
            "stock_minimo_local >= 0", name="check_stock_minimo_local_positivo"
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["productos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sucursal_id"],
            ["sucursales.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sucursal_id", "producto_id", name="uq_sucursal_producto"),
    )
    op.create_index(
        op.f("ix_inventario_sucursal_id"), "inventario_sucursal", ["id"], unique=False
    )
    op.create_table(
        "movimientos_inventario",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sucursal_id", sa.Integer(), nullable=False),
        sa.Column("producto_id", sa.Integer(), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column("tipo_movimiento", sa.String(length=20), nullable=False),
        sa.Column("motivo", sa.String(length=100), nullable=False),
        sa.Column("stock_resultante", sa.Integer(), nullable=False),
        sa.Column(
            "fecha_movimiento",
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "tipo_movimiento IN ('INGRESO', 'RETIRO')",
            name="check_tipo_movimiento_valido",
        ),
        sa.CheckConstraint("cantidad > 0", name="check_cantidad_movimiento_positiva"),
        sa.CheckConstraint(
            "stock_resultante >= 0", name="check_stock_resultante_positivo"
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["productos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sucursal_id"],
            ["sucursales.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_movimientos_inventario_id"),
        "movimientos_inventario",
        ["id"],
        unique=False,
    )
    op.create_table(
        "ordenes_compra",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("proveedor_id", sa.Integer(), nullable=False),
        sa.Column("sucursal_destino_id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("estado", sa.String(length=50), nullable=False),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("fecha_recepcion", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["proveedor_id"],
            ["proveedores.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sucursal_destino_id"],
            ["sucursales.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ordenes_compra_id"), "ordenes_compra", ["id"], unique=False
    )
    op.create_table(
        "transferencias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sucursal_origen_id", sa.Integer(), nullable=False),
        sa.Column("sucursal_destino_id", sa.Integer(), nullable=False),
        sa.Column("usuario_solicitante_id", sa.Integer(), nullable=False),
        sa.Column("estado", sa.String(length=50), nullable=False),
        sa.Column("prioridad", sa.String(length=20), nullable=False),
        sa.Column("transportista", sa.String(length=150), nullable=True),
        sa.Column("fecha_estimada_llegada", sa.DateTime(), nullable=True),
        sa.Column("fecha_real_llegada", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["sucursal_destino_id"],
            ["sucursales.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sucursal_origen_id"],
            ["sucursales.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_solicitante_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transferencias_id"), "transferencias", ["id"], unique=False
    )
    op.create_table(
        "ventas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sucursal_id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column(
            "fecha_venta", sa.DateTime(), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("total_venta", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.CheckConstraint("total_venta >= 0", name="check_total_venta_positivo"),
        sa.ForeignKeyConstraint(
            ["sucursal_id"],
            ["sucursales.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ventas_id"), "ventas", ["id"], unique=False)
    op.create_table(
        "detalle_orden_compra",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("orden_compra_id", sa.Integer(), nullable=False),
        sa.Column("producto_id", sa.Integer(), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column("precio_unitario", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("descuento", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.CheckConstraint("cantidad > 0", name="check_cantidad_orden_positiva"),
        sa.CheckConstraint(
            "precio_unitario >= 0", name="check_precio_unitario_orden_positivo"
        ),
        sa.ForeignKeyConstraint(
            ["orden_compra_id"], ["ordenes_compra.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["productos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_detalle_orden_compra_id"), "detalle_orden_compra", ["id"], unique=False
    )
    op.create_table(
        "detalle_transferencia",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transferencia_id", sa.Integer(), nullable=False),
        sa.Column("producto_id", sa.Integer(), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column("cantidad_solicitada", sa.Integer(), nullable=False),
        sa.Column("cantidad_enviada", sa.Integer(), nullable=False),
        sa.Column("cantidad_recibida", sa.Integer(), nullable=False),
        sa.Column("faltantes", sa.Integer(), nullable=False),
        sa.Column("tratamiento_faltante", sa.String(length=50), nullable=True),
        sa.CheckConstraint("cantidad > 0", name="check_cantidad_transf_positiva"),
        sa.CheckConstraint("cantidad_enviada >= 0", name="check_cantidad_env_positiva"),
        sa.CheckConstraint(
            "cantidad_recibida >= 0", name="check_cantidad_rec_positiva"
        ),
        sa.CheckConstraint(
            "cantidad_solicitada > 0", name="check_cantidad_solic_positiva"
        ),
        sa.CheckConstraint("faltantes >= 0", name="check_faltantes_positivo"),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["productos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transferencia_id"], ["transferencias.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_detalle_transferencia_id"),
        "detalle_transferencia",
        ["id"],
        unique=False,
    )
    op.create_table(
        "detalle_venta",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("venta_id", sa.Integer(), nullable=False),
        sa.Column("producto_id", sa.Integer(), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column("precio_unitario", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "descuento_aplicado", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.CheckConstraint("cantidad > 0", name="check_cantidad_venta_positiva"),
        sa.CheckConstraint(
            "precio_unitario >= 0", name="check_precio_unitario_venta_positivo"
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["productos.id"],
        ),
        sa.ForeignKeyConstraint(["venta_id"], ["ventas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_detalle_venta_id"), "detalle_venta", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_detalle_venta_id"), table_name="detalle_venta")
    op.drop_table("detalle_venta")
    op.drop_index(
        op.f("ix_detalle_transferencia_id"), table_name="detalle_transferencia"
    )
    op.drop_table("detalle_transferencia")
    op.drop_index(op.f("ix_detalle_orden_compra_id"), table_name="detalle_orden_compra")
    op.drop_table("detalle_orden_compra")
    op.drop_index(op.f("ix_ventas_id"), table_name="ventas")
    op.drop_table("ventas")
    op.drop_index(op.f("ix_transferencias_id"), table_name="transferencias")
    op.drop_table("transferencias")
    op.drop_index(op.f("ix_ordenes_compra_id"), table_name="ordenes_compra")
    op.drop_table("ordenes_compra")
    op.drop_index(
        op.f("ix_movimientos_inventario_id"), table_name="movimientos_inventario"
    )
    op.drop_table("movimientos_inventario")
    op.drop_index(op.f("ix_inventario_sucursal_id"), table_name="inventario_sucursal")
    op.drop_table("inventario_sucursal")
    op.drop_index(op.f("ix_usuarios_id"), table_name="usuarios")
    op.drop_index(op.f("ix_usuarios_email"), table_name="usuarios")
    op.drop_table("usuarios")
    op.drop_index(op.f("ix_productos_sku"), table_name="productos")
    op.drop_index(op.f("ix_productos_id"), table_name="productos")
    op.drop_table("productos")
    op.drop_index(op.f("ix_sucursales_nombre"), table_name="sucursales")
    op.drop_index(op.f("ix_sucursales_id"), table_name="sucursales")
    op.drop_table("sucursales")
    op.drop_index(op.f("ix_roles_nombre"), table_name="roles")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_proveedores_id"), table_name="proveedores")
    op.drop_table("proveedores")
    op.drop_index(op.f("ix_categorias_nombre"), table_name="categorias")
    op.drop_index(op.f("ix_categorias_id"), table_name="categorias")
    op.drop_table("categorias")
    # ### end Alembic commands ###
