"""Operaciones seguras, unidades, precios y cantidades decimales.

Los nuevos campos monetarios de registros históricos se inicializan en cero;
los responsables desconocidos permanecen nulos, sin atribuciones inventadas.
"""

from alembic import op
import sqlalchemy as sa

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "listas_precios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nombre"),
    )
    op.create_table(
        "precios_producto",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lista_id", sa.Integer(), nullable=False),
        sa.Column("producto_id", sa.Integer(), nullable=False),
        sa.Column("precio", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.CheckConstraint("precio >= 0", name="ck_precio_lista"),
        sa.ForeignKeyConstraint(
            ["lista_id"],
            ["listas_precios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["productos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lista_id", "producto_id", name="uq_precio_producto"),
    )
    with op.batch_alter_table("precios_producto", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_precios_producto_lista_id"), ["lista_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_precios_producto_producto_id"), ["producto_id"], unique=False
        )

    op.create_table(
        "unidades_producto",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("producto_id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=50), nullable=False),
        sa.Column("factor", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.CheckConstraint("factor > 0", name="ck_factor_unidad"),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["productos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("producto_id", "nombre", name="uq_unidad_producto"),
    )
    with op.batch_alter_table("unidades_producto", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_unidades_producto_producto_id"),
            ["producto_id"],
            unique=False,
        )

    with op.batch_alter_table("detalle_orden_compra", schema=None) as batch_op:
        batch_op.alter_column(
            "cantidad",
            existing_type=sa.INTEGER(),
            type_=sa.Numeric(precision=14, scale=3),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "precio_unitario",
            existing_type=sa.NUMERIC(precision=12, scale=2),
            type_=sa.Numeric(precision=18, scale=6),
            existing_nullable=False,
        )

    with op.batch_alter_table("detalle_transferencia", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "costo_unitario",
                sa.Numeric(precision=18, scale=6),
                server_default="0",
                nullable=False,
            )
        )
        batch_op.alter_column(
            "cantidad",
            existing_type=sa.INTEGER(),
            type_=sa.Numeric(precision=14, scale=3),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "cantidad_solicitada",
            existing_type=sa.INTEGER(),
            type_=sa.Numeric(precision=14, scale=3),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "cantidad_enviada",
            existing_type=sa.INTEGER(),
            type_=sa.Numeric(precision=14, scale=3),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "cantidad_recibida",
            existing_type=sa.INTEGER(),
            type_=sa.Numeric(precision=14, scale=3),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "faltantes",
            existing_type=sa.INTEGER(),
            type_=sa.Numeric(precision=14, scale=3),
            existing_nullable=False,
        )

    with op.batch_alter_table("detalle_venta", schema=None) as batch_op:
        batch_op.alter_column(
            "cantidad",
            existing_type=sa.INTEGER(),
            type_=sa.Numeric(precision=14, scale=3),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "precio_unitario",
            existing_type=sa.NUMERIC(precision=12, scale=2),
            type_=sa.Numeric(precision=18, scale=6),
            existing_nullable=False,
        )

    with op.batch_alter_table("inventario_sucursal", schema=None) as batch_op:
        batch_op.alter_column(
            "stock_actual",
            existing_type=sa.INTEGER(),
            type_=sa.Numeric(precision=14, scale=3),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "stock_minimo_local",
            existing_type=sa.INTEGER(),
            type_=sa.Numeric(precision=14, scale=3),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "costo_promedio_ponderado",
            existing_type=sa.NUMERIC(precision=12, scale=2),
            type_=sa.Numeric(precision=18, scale=6),
            existing_nullable=False,
        )

    with op.batch_alter_table("movimientos_inventario", schema=None) as batch_op:
        batch_op.add_column(sa.Column("usuario_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("venta_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("orden_compra_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("transferencia_id", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "costo_unitario",
                sa.Numeric(precision=18, scale=6),
                server_default="0",
                nullable=False,
            )
        )
        batch_op.alter_column(
            "cantidad",
            existing_type=sa.INTEGER(),
            type_=sa.Numeric(precision=14, scale=3),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "stock_resultante",
            existing_type=sa.INTEGER(),
            type_=sa.Numeric(precision=14, scale=3),
            existing_nullable=False,
        )
        batch_op.create_foreign_key(
            "fk_movimientos_transferencias",
            "transferencias",
            ["transferencia_id"],
            ["id"],
        )
        batch_op.create_foreign_key(
            "fk_movimientos_ordenes_compra",
            "ordenes_compra",
            ["orden_compra_id"],
            ["id"],
        )
        batch_op.create_foreign_key(
            "fk_movimientos_ventas", "ventas", ["venta_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_movimientos_usuarios", "usuarios", ["usuario_id"], ["id"]
        )

    with op.batch_alter_table("ordenes_compra", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "plazo_pago_dias", sa.Integer(), server_default="0", nullable=False
            )
        )

    with op.batch_alter_table("productos", schema=None) as batch_op:
        batch_op.alter_column(
            "stock_minimo_global",
            existing_type=sa.INTEGER(),
            type_=sa.Numeric(precision=14, scale=3),
            existing_nullable=False,
        )

    with op.batch_alter_table("transferencias", schema=None) as batch_op:
        batch_op.add_column(sa.Column("fecha_despacho", sa.DateTime(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "costo_envio",
                sa.Numeric(precision=12, scale=2),
                server_default="0",
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("ruta", sa.String(length=150), nullable=True))

    # ### end Alembic commands ###
    with op.batch_alter_table("detalle_orden_compra", schema=None) as batch_op:
        batch_op.create_check_constraint(
            "ck_descuento_rango", "descuento BETWEEN 0 AND 100"
        )

    with op.batch_alter_table("detalle_transferencia", schema=None) as batch_op:
        batch_op.create_check_constraint(
            "ck_enviado_solicitado", "cantidad_enviada <= cantidad_solicitada"
        )
        batch_op.create_check_constraint(
            "ck_recibido_enviado", "cantidad_recibida <= cantidad_enviada"
        )
        batch_op.create_check_constraint(
            "ck_faltantes_enviado", "faltantes <= cantidad_enviada"
        )

    with op.batch_alter_table("detalle_venta", schema=None) as batch_op:
        batch_op.create_check_constraint(
            "ck_descuento_aplicado_rango", "descuento_aplicado BETWEEN 0 AND 100"
        )

    with op.batch_alter_table("ordenes_compra", schema=None) as batch_op:
        batch_op.create_check_constraint("ck_plazo_pago", "plazo_pago_dias >= 0")
        batch_op.create_check_constraint(
            "ck_estado_compra", "estado IN ('PENDIENTE','RECIBIDA','CANCELADA')"
        )

    with op.batch_alter_table("transferencias", schema=None) as batch_op:
        batch_op.create_check_constraint(
            "ck_sucursales_distintas", "sucursal_origen_id <> sucursal_destino_id"
        )
        batch_op.create_check_constraint(
            "ck_estado_transferencia",
            "estado IN ('SOLICITADA','PREPARADA','EN_TRANSITO','RECIBIDA','CON_FALTANTES','CANCELADA')",
        )
        batch_op.create_check_constraint(
            "ck_prioridad_transferencia", "prioridad IN ('BAJA','MEDIA','ALTA')"
        )
        batch_op.create_check_constraint("ck_costo_envio", "costo_envio >= 0")


def downgrade():
    raise RuntimeError(
        "Migración irreversible: volver a enteros perdería cantidades decimales. Restaura un respaldo si necesitas revertir."
    )
